# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/g3-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter g3 d850 d851 d852 d855 ls990 vs985 f400,$(TARGET_DEVICE)),)

endif
