FILES_PATH := vendor/lge/f460/proprietary

PRODUCT_PACKAGES += \
    libtime_genoff 

PRODUCT_COPY_FILES += \
    $(FILES_PATH)/bin/atd:system/bin/atd \
    $(FILES_PATH)/bin/brcm-uim-sysfs:system/bin/brcm-uim-sysfs \
    $(FILES_PATH)/bin/cpfirmware:system/bin/cpfirmware \
    $(FILES_PATH)/bin/efsks:system/bin/efsks \
    $(FILES_PATH)/bin/irsc_util:system/bin/irsc_util \
    $(FILES_PATH)/bin/ks:system/bin/ks \
    $(FILES_PATH)/bin/mdm_helper:system/bin/mdm_helper \
    $(FILES_PATH)/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    $(FILES_PATH)/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    $(FILES_PATH)/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(FILES_PATH)/bin/netmgrd:system/bin/netmgrd \
    $(FILES_PATH)/bin/nl_listener:system/bin/nl_listener \
    $(FILES_PATH)/bin/port-bridge:system/bin/port-bridge \
    $(FILES_PATH)/bin/ptt_socket_app:system/bin/ptt_socket_app \
    $(FILES_PATH)/bin/qcks:system/bin/qcks \
    $(FILES_PATH)/bin/qmuxd:system/bin/qmuxd \
    $(FILES_PATH)/bin/qseecomd:system/bin/qseecomd \
    $(FILES_PATH)/bin/radish:system/bin/radish \
    $(FILES_PATH)/bin/rmnetcli:system/bin/rmnetcli \
    $(FILES_PATH)/bin/sensors.qcom:system/bin/sensors.qcom \
    $(FILES_PATH)/bin/smpl_count:system/bin/smpl_count \
    $(FILES_PATH)/bin/time_daemon:system/bin/time_daemon \
    $(FILES_PATH)/bin/wififtmd:system/bin/wififtmd \
    $(FILES_PATH)/etc/camera_config.xml:system/etc/camera_config.xml \
    $(FILES_PATH)/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg \
    $(FILES_PATH)/etc/acdbdata/Bluetooth_cal.acdb:system/etc/acdbdata/Bluetooth_cal.acdb \
    $(FILES_PATH)/etc/acdbdata/General_cal.acdb:system/etc/acdbdata/General_cal.acdb \
    $(FILES_PATH)/etc/acdbdata/Global_cal.acdb:system/etc/acdbdata/Global_cal.acdb \
    $(FILES_PATH)/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    $(FILES_PATH)/etc/acdbdata/Hdmi_cal.acdb:system/etc/acdbdata/Hdmi_cal.acdb \
    $(FILES_PATH)/etc/acdbdata/Headset_cal.acdb:system/etc/acdbdata/Headset_cal.acdb \
    $(FILES_PATH)/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    $(FILES_PATH)/etc/acdbdata/workspaceFile.qwsp:system/etc/acdbdata/workspaceFile.qwsp \
    $(FILES_PATH)/etc/bluetooth/auto_pair_devlist.conf:system/etc/bluetooth/auto_pair_devlist.conf \
    $(FILES_PATH)/etc/bluetooth/avrcp_toggle_white_list.conf:system/etc/bluetooth/avrcp_toggle_white_list.conf \
    $(FILES_PATH)/etc/bluetooth/block_avrcp_toggle_new.conf:system/etc/bluetooth/block_avrcp_toggle_new.conf \
    $(FILES_PATH)/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
    $(FILES_PATH)/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    $(FILES_PATH)/etc/bluetooth/bt_tts_list.conf:system/etc/bluetooth/bt_tts_list.conf \
    $(FILES_PATH)/etc/bluetooth/bt_vendor.conf:system/etc/bluetooth/bt_vendor.conf \
    $(FILES_PATH)/etc/bluetooth/carkit_cod_headsets.conf:system/etc/bluetooth/carkit_cod_headsets.conf \
    $(FILES_PATH)/etc/bluetooth/connect_other_profile_timeout_list.conf:system/etc/bluetooth/connect_other_profile_timeout_list.conf \
    $(FILES_PATH)/etc/bluetooth/feature_config.xml:system/etc/bluetooth/feature_config.xml \
    $(FILES_PATH)/etc/bluetooth/iop_bt.db:system/etc/bluetooth/iop_bt.db \
    $(FILES_PATH)/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(FILES_PATH)/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(FILES_PATH)/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(FILES_PATH)/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    $(FILES_PATH)/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    $(FILES_PATH)/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    $(FILES_PATH)/etc/firmware/fw_bcmdhd_mfg.bin:system/etc/firmware/fw_bcmdhd_mfg.bin \
    $(FILES_PATH)/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(FILES_PATH)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(FILES_PATH)/etc/firmware/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin \
    $(FILES_PATH)/etc/firmware/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin \
    $(FILES_PATH)/etc/firmware/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin \
    $(FILES_PATH)/etc/firmware/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin \
    $(FILES_PATH)/etc/firmware/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv \
    $(FILES_PATH)/etc/firmware/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv \
    $(FILES_PATH)/etc/firmware/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv \
    $(FILES_PATH)/etc/firmware/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img \
    $(FILES_PATH)/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    $(FILES_PATH)/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    $(FILES_PATH)/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    $(FILES_PATH)/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    $(FILES_PATH)/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    $(FILES_PATH)/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    $(FILES_PATH)/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    $(FILES_PATH)/etc/firmware/vpu.b00:system/etc/firmware/vpu.b00 \
    $(FILES_PATH)/etc/firmware/vpu.b01:system/etc/firmware/vpu.b01 \
    $(FILES_PATH)/etc/firmware/vpu.b02:system/etc/firmware/vpu.b02 \
    $(FILES_PATH)/etc/firmware/vpu.b03:system/etc/firmware/vpu.b03 \
    $(FILES_PATH)/etc/firmware/vpu.b04:system/etc/firmware/vpu.b04 \
    $(FILES_PATH)/etc/firmware/vpu.b05:system/etc/firmware/vpu.b05 \
    $(FILES_PATH)/etc/firmware/vpu.b06:system/etc/firmware/vpu.b06 \
    $(FILES_PATH)/etc/firmware/vpu.b07:system/etc/firmware/vpu.b07 \
    $(FILES_PATH)/etc/firmware/vpu.b08:system/etc/firmware/vpu.b08 \
    $(FILES_PATH)/etc/firmware/vpu.b09:system/etc/firmware/vpu.b09 \
    $(FILES_PATH)/etc/firmware/vpu.b10:system/etc/firmware/vpu.b10 \
    $(FILES_PATH)/etc/firmware/vpu.b11:system/etc/firmware/vpu.b11 \
    $(FILES_PATH)/etc/firmware/vpu.b12:system/etc/firmware/vpu.b12 \
    $(FILES_PATH)/etc/firmware/vpu.mbn:system/etc/firmware/vpu.mbn \
    $(FILES_PATH)/etc/firmware/vpu.mdt:system/etc/firmware/vpu.mdt \
    $(FILES_PATH)/etc/lgodm/gps.cfg:system/etc/lgodm/gps.cfg \
    $(FILES_PATH)/etc/lgodm/gps_sap_pdr.cfg:system/etc/lgodm/gps_sap_pdr.cfg \
    $(FILES_PATH)/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    $(FILES_PATH)/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    $(FILES_PATH)/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    $(FILES_PATH)/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    $(FILES_PATH)/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    $(FILES_PATH)/framework/tcmclient.jar:system/framework/tcmclient.jar \
    $(FILES_PATH)/lib/liballegro.so:system/lib/liballegro.so \
    $(FILES_PATH)/lib/libalmalib.so:system/lib/libalmalib.so \
    $(FILES_PATH)/lib/libatd_common.so:system/lib/libatd_common.so \
    $(FILES_PATH)/lib/libatd_corelib.so:system/lib/libatd_corelib.so \
    $(FILES_PATH)/lib/libatd_modeminterface.so:system/lib/libatd_modeminterface.so \
    $(FILES_PATH)/lib/libbcmwl.so:system/lib/libbcmwl.so \
    $(FILES_PATH)/lib/libbluedroid_bdt.so:system/lib/libbluedroid_bdt.so \
    $(FILES_PATH)/lib/libcir_driver.so:system/lib/libcir_driver.so \
    $(FILES_PATH)/lib/libdetectmodem.so:system/lib/libdetectmodem.so \
    $(FILES_PATH)/lib/libdiagd_client.so:system/lib/libdiagd_client.so \
    $(FILES_PATH)/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
    $(FILES_PATH)/lib/libfrst.so:system/lib/libfrst.so \
    $(FILES_PATH)/lib/libgps.utils.so:system/lib/libgps.utils.so \
    $(FILES_PATH)/lib/libHDR.so:system/lib/libHDR.so \
    $(FILES_PATH)/lib/libimsmedia.so:system/lib/libimsmedia.so \
    $(FILES_PATH)/lib/libimsmmpf.so:system/lib/libimsmmpf.so \
    $(FILES_PATH)/lib/libims.so:system/lib/libims.so \
    $(FILES_PATH)/lib/liblgcamera_jni.so:system/lib/liblgcamera_jni.so \
    $(FILES_PATH)/lib/liblgehdcpek.so:system/lib/liblgehdcpek.so \
    $(FILES_PATH)/lib/liblgerft.so:system/lib/liblgerft.so \
    $(FILES_PATH)/lib/liblgftmitem.so:system/lib/liblgftmitem.so \
    $(FILES_PATH)/lib/liblgomxdecoder_musicam.so:system/lib/liblgomxdecoder_musicam.so \
    $(FILES_PATH)/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    $(FILES_PATH)/lib/libloc_core.so:system/lib/libloc_core.so \
    $(FILES_PATH)/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    $(FILES_PATH)/lib/libloc_eng.so:system/lib/libloc_eng.so \
    $(FILES_PATH)/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    $(FILES_PATH)/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    $(FILES_PATH)/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    $(FILES_PATH)/lib/libmorpho_image_stab31.so:system/lib/libmorpho_image_stab31.so \
    $(FILES_PATH)/lib/libmorpho_noise_reduction.so:system/lib/libmorpho_noise_reduction.so \
    $(FILES_PATH)/lib/libmorpho_video_denoiser.so:system/lib/libmorpho_video_denoiser.so \
    $(FILES_PATH)/lib/libnetmgr.so:system/lib/libnetmgr.so \
    $(FILES_PATH)/lib/libqomx_core.so:system/lib/libqomx_core.so \
    $(FILES_PATH)/lib/libqti_performance.so:system/lib/libqti_performance.so \
    $(FILES_PATH)/lib/libril.so:system/lib/libril.so \
    $(FILES_PATH)/lib/libuicc.so:system/lib/libuicc.so \
    $(FILES_PATH)/lib/libunified_sysfs_pm.so:system/lib/libunified_sysfs_pm.so \
    $(FILES_PATH)/lib/libvss_bsp_qcci.so:system/lib/libvss_bsp_qcci.so \
    $(FILES_PATH)/lib/libvss_common_core.so:system/lib/libvss_common_core.so \
    $(FILES_PATH)/lib/libvss_common_idl.so:system/lib/libvss_common_idl.so \
    $(FILES_PATH)/lib/libvss_common_iface.so:system/lib/libvss_common_iface.so \
    $(FILES_PATH)/lib/libvss_dmi_qcci.so:system/lib/libvss_dmi_qcci.so \
    $(FILES_PATH)/lib/libvss_gnss_qcci.so:system/lib/libvss_gnss_qcci.so \
    $(FILES_PATH)/lib/libvss_ims_qcci.so:system/lib/libvss_ims_qcci.so \
    $(FILES_PATH)/lib/libvss_nv_core.so:system/lib/libvss_nv_core.so \
    $(FILES_PATH)/lib/libvss_nv_idl.so:system/lib/libvss_nv_idl.so \
    $(FILES_PATH)/lib/libvss_nv_iface.so:system/lib/libvss_nv_iface.so \
    $(FILES_PATH)/lib/libvss_resim_core.so:system/lib/libvss_resim_core.so \
    $(FILES_PATH)/lib/libvss_resim_idl.so:system/lib/libvss_resim_idl.so \
    $(FILES_PATH)/lib/libvss_resim_iface.so:system/lib/libvss_resim_iface.so \
    $(FILES_PATH)/lib/libwvoemprov.so:system/lib/libwvoemprov.so \
    $(FILES_PATH)/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    $(FILES_PATH)/lib/hw/camera.apq8084.so:system/lib/hw/camera.apq8084.so \
    $(FILES_PATH)/lib/hw/consumerir.apq8084.so:system/lib/hw/consumerir.apq8084.so \
    $(FILES_PATH)/lib/hw/gps.apq8084.so:system/lib/hw/gps.apq8084.so \
    $(FILES_PATH)/priv-app/qcrilmsgtunnel:system/priv-app/qcrilmsgtunnel \
    $(FILES_PATH)/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk:system/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk \
    $(FILES_PATH)/vendor/bin/qti:system/vendor/bin/qti \
    $(FILES_PATH)/vendor/bin/sound_trigger_test:system/vendor/bin/sound_trigger_test \
    $(FILES_PATH)/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    $(FILES_PATH)/vendor/firmware/a420_pfp.fw:system/vendor/firmware/a420_pfp.fw \
    $(FILES_PATH)/vendor/firmware/a420_pm4.fw:system/vendor/firmware/a420_pm4.fw \
    $(FILES_PATH)/vendor/firmware/BCM4354_003.001.012.0197.0000_LGE_Tiger_6_TEST_ONLY.hcd:system/vendor/firmware/BCM4354_003.001.012.0197.0000_LGE_Tiger_6_TEST_ONLY.hcd \
    $(FILES_PATH)/vendor/firmware/BCM4354A2_001.003.015.0044.0054_LGE_Tiger_6_BT41_ORC.hcd:system/vendor/firmware/BCM4354A2_001.003.015.0044.0054_LGE_Tiger_6_BT41_ORC.hcd \
    $(FILES_PATH)/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    $(FILES_PATH)/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    $(FILES_PATH)/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    $(FILES_PATH)/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(FILES_PATH)/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    $(FILES_PATH)/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    $(FILES_PATH)/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    $(FILES_PATH)/vendor/lib/libactuator_dw9716_camcorder.so:system/vendor/lib/libactuator_dw9716_camcorder.so \
    $(FILES_PATH)/vendor/lib/libactuator_dw9716_camera.so:system/vendor/lib/libactuator_dw9716_camera.so \
    $(FILES_PATH)/vendor/lib/libactuator_dw9716.so:system/vendor/lib/libactuator_dw9716.so \
    $(FILES_PATH)/vendor/lib/libactuator_iu074_camcorder.so:system/vendor/lib/libactuator_iu074_camcorder.so \
    $(FILES_PATH)/vendor/lib/libactuator_iu074_camera.so:system/vendor/lib/libactuator_iu074_camera.so \
    $(FILES_PATH)/vendor/lib/libactuator_iu074.so:system/vendor/lib/libactuator_iu074.so \
    $(FILES_PATH)/vendor/lib/libactuator_ov12830_camcorder.so:system/vendor/lib/libactuator_ov12830_camcorder.so \
    $(FILES_PATH)/vendor/lib/libactuator_ov12830_camera.so:system/vendor/lib/libactuator_ov12830_camera.so \
    $(FILES_PATH)/vendor/lib/libactuator_ov12830.so:system/vendor/lib/libactuator_ov12830.so \
    $(FILES_PATH)/vendor/lib/libactuator_ov8825_camcorder.so:system/vendor/lib/libactuator_ov8825_camcorder.so \
    $(FILES_PATH)/vendor/lib/libactuator_ov8825_camera.so:system/vendor/lib/libactuator_ov8825_camera.so \
    $(FILES_PATH)/vendor/lib/libactuator_ov8825.so:system/vendor/lib/libactuator_ov8825.so \
    $(FILES_PATH)/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    $(FILES_PATH)/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so \
    $(FILES_PATH)/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    $(FILES_PATH)/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(FILES_PATH)/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(FILES_PATH)/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(FILES_PATH)/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    $(FILES_PATH)/vendor/lib/libasn1cper.so:system/vendor/lib/libasn1cper.so \
    $(FILES_PATH)/vendor/lib/libasn1crt.so:system/vendor/lib/libasn1crt.so \
    $(FILES_PATH)/vendor/lib/libasn1crtx.so:system/vendor/lib/libasn1crtx.so \
    $(FILES_PATH)/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(FILES_PATH)/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    $(FILES_PATH)/vendor/lib/libavenhancements.so:system/vendor/lib/libavenhancements.so \
    $(FILES_PATH)/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    $(FILES_PATH)/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    $(FILES_PATH)/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(FILES_PATH)/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(FILES_PATH)/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    $(FILES_PATH)/vendor/lib/libc2d30-a5xx.so:system/vendor/lib/libc2d30-a5xx.so \
    $(FILES_PATH)/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_120fps_cpp.so:system/vendor/lib/libchromatix_imx135_120fps_cpp.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_common.so:system/vendor/lib/libchromatix_imx135_30fps_common.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_cpp.so:system/vendor/lib/libchromatix_imx135_30fps_cpp.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_default_video.so:system/vendor/lib/libchromatix_imx135_30fps_default_video.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_hfr_120.so:system/vendor/lib/libchromatix_imx135_30fps_hfr_120.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_hfr_60.so:system/vendor/lib/libchromatix_imx135_30fps_hfr_60.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_liveshot.so:system/vendor/lib/libchromatix_imx135_30fps_liveshot.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_mms_video.so:system/vendor/lib/libchromatix_imx135_30fps_mms_video.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_preview.so:system/vendor/lib/libchromatix_imx135_30fps_preview.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_snapshot.so:system/vendor/lib/libchromatix_imx135_30fps_snapshot.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_uhd_cpp.so:system/vendor/lib/libchromatix_imx135_30fps_uhd_cpp.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_uhd_video.so:system/vendor/lib/libchromatix_imx135_30fps_uhd_video.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_video_dualrec.so:system/vendor/lib/libchromatix_imx135_30fps_video_dualrec.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_video_hdr.so:system/vendor/lib/libchromatix_imx135_30fps_video_hdr.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_video_hd.so:system/vendor/lib/libchromatix_imx135_30fps_video_hd.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_30fps_video_qtr.so:system/vendor/lib/libchromatix_imx135_30fps_video_qtr.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx135_cpp.so:system/vendor/lib/libchromatix_imx135_cpp.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_30fps_cpp.so:system/vendor/lib/libchromatix_imx208_30fps_cpp.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_common.so:system/vendor/lib/libchromatix_imx208_common.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_cpp.so:system/vendor/lib/libchromatix_imx208_cpp.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_default_video.so:system/vendor/lib/libchromatix_imx208_default_video.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_liveshot.so:system/vendor/lib/libchromatix_imx208_liveshot.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_mms_video.so:system/vendor/lib/libchromatix_imx208_mms_video.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_preview.so:system/vendor/lib/libchromatix_imx208_preview.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_snapshot.so:system/vendor/lib/libchromatix_imx208_snapshot.so \
    $(FILES_PATH)/vendor/lib/libchromatix_imx208_vt.so:system/vendor/lib/libchromatix_imx208_vt.so \
    $(FILES_PATH)/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    $(FILES_PATH)/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    $(FILES_PATH)/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    $(FILES_PATH)/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    $(FILES_PATH)/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    $(FILES_PATH)/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    $(FILES_PATH)/vendor/lib/libconnctrl.so:system/vendor/lib/libconnctrl.so \
    $(FILES_PATH)/vendor/lib/libcsd-client.so:system/vendor/lib/libcsd-client.so \
    $(FILES_PATH)/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    $(FILES_PATH)/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(FILES_PATH)/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    $(FILES_PATH)/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    $(FILES_PATH)/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    $(FILES_PATH)/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    $(FILES_PATH)/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    $(FILES_PATH)/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    $(FILES_PATH)/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
    $(FILES_PATH)/vendor/lib/libdpmtcm.so:system/vendor/lib/libdpmtcm.so \
    $(FILES_PATH)/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    $(FILES_PATH)/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    $(FILES_PATH)/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    $(FILES_PATH)/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(FILES_PATH)/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(FILES_PATH)/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    $(FILES_PATH)/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    $(FILES_PATH)/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(FILES_PATH)/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    $(FILES_PATH)/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    $(FILES_PATH)/vendor/lib/libgdtap.so:system/vendor/lib/libgdtap.so \
    $(FILES_PATH)/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    $(FILES_PATH)/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(FILES_PATH)/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    $(FILES_PATH)/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(FILES_PATH)/vendor/lib/lib-imscamera.so:system/vendor/lib/lib-imscamera.so \
    $(FILES_PATH)/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    $(FILES_PATH)/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    $(FILES_PATH)/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    $(FILES_PATH)/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    $(FILES_PATH)/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
    $(FILES_PATH)/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    $(FILES_PATH)/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    $(FILES_PATH)/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    $(FILES_PATH)/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(FILES_PATH)/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(FILES_PATH)/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    $(FILES_PATH)/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    $(FILES_PATH)/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
    $(FILES_PATH)/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    $(FILES_PATH)/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    $(FILES_PATH)/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    $(FILES_PATH)/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so \
    $(FILES_PATH)/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    $(FILES_PATH)/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    $(FILES_PATH)/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    $(FILES_PATH)/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_imx135_eeprom.so:system/vendor/lib/libmmcamera_imx135_eeprom.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_imx208.so:system/vendor/lib/libmmcamera_imx208.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_abf44.so:system/vendor/lib/libmmcamera_isp_abf44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_bcc44.so:system/vendor/lib/libmmcamera_isp_bcc44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_be_stats44.so:system/vendor/lib/libmmcamera_isp_be_stats44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_bf_scale_stats44.so:system/vendor/lib/libmmcamera_isp_bf_scale_stats44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_bf_stats44.so:system/vendor/lib/libmmcamera_isp_bf_stats44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_bg_stats44.so:system/vendor/lib/libmmcamera_isp_bg_stats44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_bpc44.so:system/vendor/lib/libmmcamera_isp_bpc44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_clf44.so:system/vendor/lib/libmmcamera_isp_clf44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_color_correct40.so:system/vendor/lib/libmmcamera_isp_color_correct40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_cs_stats44.so:system/vendor/lib/libmmcamera_isp_cs_stats44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_demosaic44.so:system/vendor/lib/libmmcamera_isp_demosaic44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_gamma44.so:system/vendor/lib/libmmcamera_isp_gamma44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_ihist_stats44.so:system/vendor/lib/libmmcamera_isp_ihist_stats44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_ltm44.so:system/vendor/lib/libmmcamera_isp_ltm44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_luma_adaptation40.so:system/vendor/lib/libmmcamera_isp_luma_adaptation40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_rs_stats44.so:system/vendor/lib/libmmcamera_isp_rs_stats44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_scaler_encoder44.so:system/vendor/lib/libmmcamera_isp_scaler_encoder44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_isp_wb40.so:system/vendor/lib/libmmcamera_isp_wb40.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_ubifocus_lib.so:system/vendor/lib/libmmcamera_ubifocus_lib.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_vpu_module.so:system/vendor/lib/libmmcamera_vpu_module.so \
    $(FILES_PATH)/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    $(FILES_PATH)/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    $(FILES_PATH)/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    $(FILES_PATH)/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    $(FILES_PATH)/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
    $(FILES_PATH)/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
    $(FILES_PATH)/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    $(FILES_PATH)/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    $(FILES_PATH)/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
    $(FILES_PATH)/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
    $(FILES_PATH)/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
    $(FILES_PATH)/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(FILES_PATH)/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    $(FILES_PATH)/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    $(FILES_PATH)/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    $(FILES_PATH)/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(FILES_PATH)/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    $(FILES_PATH)/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    $(FILES_PATH)/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    $(FILES_PATH)/vendor/lib/libMMScreenCapture.so:system/vendor/lib/libMMScreenCapture.so \
    $(FILES_PATH)/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
    $(FILES_PATH)/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
    $(FILES_PATH)/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
    $(FILES_PATH)/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    $(FILES_PATH)/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    $(FILES_PATH)/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    $(FILES_PATH)/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    $(FILES_PATH)/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    $(FILES_PATH)/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    $(FILES_PATH)/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    $(FILES_PATH)/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
    $(FILES_PATH)/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    $(FILES_PATH)/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    $(FILES_PATH)/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(FILES_PATH)/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    $(FILES_PATH)/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(FILES_PATH)/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    $(FILES_PATH)/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    $(FILES_PATH)/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(FILES_PATH)/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(FILES_PATH)/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(FILES_PATH)/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    $(FILES_PATH)/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(FILES_PATH)/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(FILES_PATH)/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(FILES_PATH)/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(FILES_PATH)/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(FILES_PATH)/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(FILES_PATH)/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(FILES_PATH)/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(FILES_PATH)/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(FILES_PATH)/vendor/lib/libQtiTether.so:system/vendor/lib/libQtiTether.so \
    $(FILES_PATH)/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    $(FILES_PATH)/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
    $(FILES_PATH)/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
    $(FILES_PATH)/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    $(FILES_PATH)/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    $(FILES_PATH)/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    $(FILES_PATH)/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    $(FILES_PATH)/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    $(FILES_PATH)/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(FILES_PATH)/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    $(FILES_PATH)/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    $(FILES_PATH)/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    $(FILES_PATH)/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    $(FILES_PATH)/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    $(FILES_PATH)/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    $(FILES_PATH)/vendor/lib/libscve_stub.so:system/vendor/lib/libscve_stub.so \
    $(FILES_PATH)/vendor/lib/lib-sec-disp.so:system/vendor/lib/lib-sec-disp.so \
    $(FILES_PATH)/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so \
    $(FILES_PATH)/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
    $(FILES_PATH)/vendor/lib/libsecureuisvc_jni.so:system/vendor/lib/libsecureuisvc_jni.so \
    $(FILES_PATH)/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so \
    $(FILES_PATH)/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    $(FILES_PATH)/vendor/lib/libsensor_lge_cal.so:system/vendor/lib/libsensor_lge_cal.so \
    $(FILES_PATH)/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    $(FILES_PATH)/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    $(FILES_PATH)/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    $(FILES_PATH)/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    $(FILES_PATH)/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
    $(FILES_PATH)/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    $(FILES_PATH)/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
    $(FILES_PATH)/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    $(FILES_PATH)/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    $(FILES_PATH)/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    $(FILES_PATH)/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    $(FILES_PATH)/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    $(FILES_PATH)/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
    $(FILES_PATH)/vendor/lib/libubifocus.so:system/vendor/lib/libubifocus.so \
    $(FILES_PATH)/vendor/lib/libvcel.so:system/vendor/lib/libvcel.so \
    $(FILES_PATH)/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    $(FILES_PATH)/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    $(FILES_PATH)/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
    $(FILES_PATH)/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
    $(FILES_PATH)/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
    $(FILES_PATH)/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
    $(FILES_PATH)/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
    $(FILES_PATH)/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
    $(FILES_PATH)/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
    $(FILES_PATH)/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
    $(FILES_PATH)/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
    $(FILES_PATH)/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
    $(FILES_PATH)/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
    $(FILES_PATH)/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
    $(FILES_PATH)/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
    $(FILES_PATH)/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    $(FILES_PATH)/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    $(FILES_PATH)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(FILES_PATH)/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    $(FILES_PATH)/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    $(FILES_PATH)/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    $(FILES_PATH)/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    $(FILES_PATH)/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    $(FILES_PATH)/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    $(FILES_PATH)/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    $(FILES_PATH)/vendor/lib/hw/activity_recognition.apq8084.so:system/vendor/lib/hw/activity_recognition.apq8084.so \
    $(FILES_PATH)/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    $(FILES_PATH)/vendor/lib/hw/sensors.apq8084.so:system/vendor/lib/hw/sensors.apq8084.so \
    $(FILES_PATH)/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    $(FILES_PATH)/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    $(FILES_PATH)/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    $(FILES_PATH)/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    $(FILES_PATH)/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    $(FILES_PATH)/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    $(FILES_PATH)/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd
