# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/g2-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter g2 d800 d801 d802 d803 f320 l01f ls980 vs980,$(TARGET_DEVICE)),)

endif
