# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/e975/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/e975/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/lge/e975/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/lge/e975/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/e975/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/lge/e975/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/lge/e975/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/lge/e975/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/lge/e975/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/lge/e975/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/lge/e975/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/e975/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/lge/e975/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/e975/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/e975/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/e975/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/lge/e975/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/lge/e975/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/lge/e975/proprietary/lib/libmorpho_movie_stabilization.so:system/lib/libmorpho_movie_stabilization.so \
    vendor/lge/e975/proprietary/lib/libmorpho_noise_reduction.so:system/lib/libmorpho_noise_reduction.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx091_zsl.so:system/lib/libchromatix_imx091_zsl.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx111_default_video.so:system/lib/libchromatix_imx111_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx111_preview.so:system/lib/libchromatix_imx111_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx111_zsl.so:system/lib/libchromatix_imx111_zsl.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx119_default_video.so:system/lib/libchromatix_imx119_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx119_preview.so:system/lib/libchromatix_imx119_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx119_vt.so:system/lib/libchromatix_imx119_vt.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx132_default_video.so:system/lib/libchromatix_imx132_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_imx132_preview.so:system/lib/libchromatix_imx132_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/lge/e975/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/lge/e975/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/e975/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/lge/e975/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/lge/e975/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/lge/e975/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/lge/e975/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/lge/e975/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/lge/e975/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/lge/e975/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/e975/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/lge/e975/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/lge/e975/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/lge/e975/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/e975/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/lge/e975/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/lge/e975/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/lge/e975/proprietary/lib/libAKM.so:system/lib/libAKM.so \
    vendor/lge/e975/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/lge/e975/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    vendor/lge/e975/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
    vendor/lge/e975/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/lge/e975/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/lge/e975/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/lge/e975/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/lge/e975/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/lge/e975/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/lge/e975/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/lge/e975/proprietary/lib/libsensor_user_cal.so:system/lib/libsensor_user_cal.so \
    vendor/lge/e975/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/lge/e975/proprietary/lib/lib_dlb_msd.so:system/lib/lib_dlb_msd.so \
    vendor/lge/e975/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/lge/e975/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
    vendor/lge/e975/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
    vendor/lge/e975/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/lge/e975/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/lge/e975/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/lge/e975/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/lge/e975/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/lge/e975/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/lge/e975/proprietary/bin/efsks:system/bin/efsks \
    vendor/lge/e975/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/lge/e975/proprietary/bin/ks:system/bin/ks \
    vendor/lge/e975/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/e975/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/lge/e975/proprietary/bin/qcks:system/bin/qcks \
    vendor/lge/e975/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/lge/e975/proprietary/bin/radish:system/bin/radish \
    vendor/lge/e975/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/lge/e975/proprietary/bin/thermald:system/bin/thermald \
    vendor/lge/e975/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/e975/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/e975/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/lge/e975/proprietary/bin/rild:system/bin/rild \
    vendor/lge/e975/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/lge/e975/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/lge/e975/proprietary/bin/qosmgr:system/bin/qosmgr \
    vendor/lge/e975/proprietary/vendor/firmware/a300_pfp.fw:system/vendor/firmware/a300_pfp.fw \
    vendor/lge/e975/proprietary/vendor/firmware/a300_pm4.fw:system/vendor/firmware/a300_pm4.fw \
    vendor/lge/e975/proprietary/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/lge/e975/proprietary/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/lge/e975/proprietary/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/lge/e975/proprietary/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/lge/e975/proprietary/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/lge/e975/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/lge/e975/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/lge/e975/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/lge/e975/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/lge/e975/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/lge/e975/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/lge/e975/proprietary/etc/firmware/wcd9310/wcd9310_anc.bin:system/etc/firmware/wcd9310/wcd9310_anc.bin \
    vendor/lge/e975/proprietary/etc/firmware/wcd9310/wcd9310_mbhc.bin:system/etc/firmware/wcd9310/wcd9310_mbhc.bin \
    vendor/lge/e975/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/lge/e975/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/lge/e975/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/lge/e975/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/lge/e975/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/lge/e975/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/lge/e975/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
    vendor/lge/e975/proprietary/lib/liblgftmitem.so:system/lib/liblgftmitem.so \
    vendor/lge/e975/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
    vendor/lge/e975/proprietary/lib/libllvm-arm.so:system/lib/libllvm-arm.so \
    vendor/lge/e975/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/lge/e975/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/lge/e975/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/lge/e975/proprietary/lib/libgsl.so:system/lib/libgsl.so

ifeq ($(TARGET_DEVICE),e975)
PRODUCT_COPY_FILES += \
    vendor/lge/e975/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so
endif

ifeq ($(TARGET_DEVICE),e973)
PRODUCT_COPY_FILES += \
    vendor/lge/e975/proprietary/vendor/firmware/libpn544_fw_e973.so:system/vendor/firmware/libpn544_fw.so
endif

ifeq ($(TARGET_DEVICE),e970)
PRODUCT_COPY_FILES += \
    vendor/lge/e975/proprietary/vendor/firmware/libpn544_fw_e970.so:system/vendor/firmware/libpn544_fw.so
endif

ifeq ($(TARGET_DEVICE),ls970)
PRODUCT_COPY_FILES += \
    vendor/lge/e975/proprietary/vendor/firmware/libpn544_fw_ls970.so:system/vendor/firmware/libpn544_fw.so
endif
