# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/g5-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter g5 h830 h850 rs988,$(TARGET_DEVICE)),)

endif
