# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/v20-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter v20 h918 h910,$(TARGET_DEVICE)),)

ifneq ($(TARGET_HAVE_QC_PERF),true)
endif
endif
