# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/g6-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter g6 h870 h872 us997,$(TARGET_DEVICE)),)

endif
