# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/e739/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/lge/e739/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/lge/e739/proprietary/libv8.so:obj/lib/libv8.so

# All the blobs necessary for e739
PRODUCT_COPY_FILES += \
    vendor/lge/e739/proprietary/ami304d:system/bin/ami304d \
    vendor/lge/e739/proprietary/rmt_storage:system/bin/rmt_storage \
    vendor/lge/e739/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/lge/e739/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/lge/e739/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/lge/e739/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/lge/e739/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/lge/e739/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/lge/e739/proprietary/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/lge/e739/proprietary/libC2D2.so:system/lib/libC2D2.so \
    vendor/lge/e739/proprietary/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/lge/e739/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/lge/e739/proprietary/libgemini.so:system/lib/libgemini.so \
    vendor/lge/e739/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/e739/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/e739/proprietary/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/lge/e739/proprietary/netmgrd:system/bin/netmgrd \
    vendor/lge/e739/proprietary/qmuxd:system/bin/qmuxd \
    vendor/lge/e739/proprietary/rild:system/bin/rild \
    vendor/lge/e739/proprietary/libauth.so:system/lib/libauth.so \
    vendor/lge/e739/proprietary/libbcmwl.so:system/lib/libbcmwl.so \
    vendor/lge/e739/proprietary/libcm.so:system/lib/libcm.so \
    vendor/lge/e739/proprietary/libcne.so:system/lib/libcne.so \
    vendor/lge/e739/proprietary/libcneutils.so:system/lib/libcneutils.so \
    vendor/lge/e739/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/lge/e739/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so  \
    vendor/lge/e739/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/lge/e739/proprietary/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/lge/e739/proprietary/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/e739/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/lge/e739/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/lge/e739/proprietary/libidl.so:system/lib/libidl.so \
    vendor/lge/e739/proprietary/liblgdrm.so:system/lib/liblgdrm.so \
    vendor/lge/e739/proprietary/liblge_security.so:system/lib/liblge_security.so \
    vendor/lge/e739/proprietary/liblgeat.so:system/lib/liblgeat.so \
    vendor/lge/e739/proprietary/liblgenfctest.so:system/lib/liblgenfctest.so \
    vendor/lge/e739/proprietary/liblgerft.so:system/lib/liblgerft.so \
    vendor/lge/e739/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/lge/e739/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/e739/proprietary/libnfc.so:system/lib/libnfc.so \
    vendor/lge/e739/proprietary/libnv.so:system/lib/libnv.so \
    vendor/lge/e739/proprietary/libnv.so:obj/lib/libnv.so \
    vendor/lge/e739/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/lge/e739/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/lge/e739/proprietary/liboncrpc.so:obj/lib/liboncrpc.so \
    vendor/lge/e739/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/lge/e739/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/lge/e739/proprietary/libqdp.so:system/lib/libqdp.so \
    vendor/lge/e739/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/lge/e739/proprietary/librefcne.so:system/lib/librefcne.so \
    vendor/lge/e739/proprietary/libril.so:system/lib/libril.so \
    vendor/lge/e739/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/lge/e739/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/e739/proprietary/libwms.so:system/lib/libwms.so \
    vendor/lge/e739/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/lge/e739/proprietary/libv8.so:system/lib/libv8.so \
    vendor/lge/e739/proprietary/camera.victor.so:system/lib/hw/camera.victor.so \
    vendor/lge/e739/proprietary/libchromatix_mt9p017_preview.so:system/lib/libchromatix_mt9p017_preview.so \
    vendor/lge/e739/proprietary/libchromatix_mt9p017_video.so:system/lib/libchromatix_mt9p017_video.so \
    vendor/lge/e739/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/e739/proprietary/chargerlogo:/sbin/chargerlogo \
    vendor/lge/e739/proprietary/wallpaper:/sbin/wallpaper \
    vendor/lge/e739/proprietary/firmware/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
    vendor/lge/e739/proprietary/firmware/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/lge/e739/proprietary/firmware/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/lge/e739/proprietary/firmware/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/lge/e739/proprietary/firmware/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/lge/e739/proprietary/firmware/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/lge/e739/proprietary/firmware/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
    vendor/lge/e739/proprietary/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/lge/e739/proprietary/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/lge/e739/proprietary/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/lge/e739/proprietary/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/lge/e739/proprietary/firmware/nvram.txt:system/etc/wl/nvram.txt \
    vendor/lge/e739/proprietary/firmware/rtecdc-apsta.bin:system/etc/firmware/rtecdc-apsta.bin \
    vendor/lge/e739/proprietary/firmware/rtecdc.bin:system/etc/firmware/rtecdc.bin \
    vendor/lge/e739/proprietary/firmware/BCM4330B1_002.001.003.0243.0305.hcd:system/etc/firmware/BCM4330B1_002.001.003.0243.0305.hcd
