# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/p880/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/p880/proprietary/bin/hdmid:system/bin/hdmid \
    vendor/lge/p880/proprietary/bin/lgdrmserver:system/bin/lgdrmserver \
    vendor/lge/p880/proprietary/bin/lgsecclkserver:system/bin/lgsecclkserver \
    vendor/lge/p880/proprietary/bin/nvcpud:system/bin/nvcpud \
    vendor/lge/p880/proprietary/bin/rild:system/bin/rild \
    vendor/lge/p880/proprietary/bin/tf_daemon:system/bin/tf_daemon \
    vendor/lge/p880/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
    vendor/lge/p880/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
    vendor/lge/p880/proprietary/lib/hw/lights.x3.so:system/lib/hw/lights.x3.so \
    vendor/lge/p880/proprietary/lib/hw/sensors.tegra.so:system/lib/hw/sensors.tegra.so \
    vendor/lge/p880/proprietary/lib/hw/audio_policy.vendor.tegra.so:system/lib/hw/audio_policy.vendor.tegra.so \
    vendor/lge/p880/proprietary/lib/hw/audio.primary_vendor.tegra.so:system/lib/hw/audio.primary_vendor.tegra.so \
    vendor/lge/p880/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/lge/p880/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/lge/p880/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
    vendor/lge/p880/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/lge/p880/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/lge/p880/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/lge/p880/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
    vendor/lge/p880/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/lge/p880/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/lge/p880/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/lge/p880/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
    vendor/lge/p880/proprietary/lib/liblgsecclk.so:system/lib/liblgsecclk.so \
    vendor/lge/p880/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/lge/p880/proprietary/lib/libmlFIFO.so:system/lib/libmlFIFO.so \
    vendor/lge/p880/proprietary/lib/libami.so:system/lib/libami.so \
    vendor/lge/p880/proprietary/lib/libami_sensor_mw.so:system/lib/libami_sensor_mw.so \
    vendor/lge/p880/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/lge/p880/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
    vendor/lge/p880/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
    vendor/lge/p880/proprietary/lib/libnvcapclk.so:system/lib/libnvcapclk.so \
    vendor/lge/p880/proprietary/lib/libnvcap.so:system/lib/libnvcap.so \
    vendor/lge/p880/proprietary/lib/libnvcap_video.so:system/lib/libnvcap_video.so \
    vendor/lge/p880/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
    vendor/lge/p880/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
    vendor/lge/p880/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/lge/p880/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/lge/p880/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/lge/p880/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/lge/p880/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
    vendor/lge/p880/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/lge/p880/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
    vendor/lge/p880/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/lge/p880/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/lge/p880/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/lge/p880/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/lge/p880/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/lge/p880/proprietary/lib/lge-ril.so:system/lib/lge-ril.so \
    vendor/lge/p880/proprietary/lib/libini.so:system/lib/libini.so \
    vendor/lge/p880/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/p880/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
    vendor/lge/p880/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/lge/p880/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/lge/p880/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/lge/p880/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/lge/p880/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/lge/p880/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
    vendor/lge/p880/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
    vendor/lge/p880/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
    vendor/lge/p880/proprietary/lib/lib-lge-drm.so:system/lib/lib-lge-drm.so \
    vendor/lge/p880/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/lge/p880/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
    vendor/lge/p880/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
    vendor/lge/p880/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
    vendor/lge/p880/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
    vendor/lge/p880/proprietary/lib/libnvmmlite_msaudio.so:system/lib/libnvmmlite_msaudio.so \
    vendor/lge/p880/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
    vendor/lge/p880/proprietary/etc/firmware/nvavp_aud_ucode.bin:system/etc/firmware/nvavp_aud_ucode.bin \
    vendor/lge/p880/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
    vendor/lge/p880/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
    vendor/lge/p880/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
    vendor/lge/p880/proprietary/etc/firmware/nvavp_vid_ucode.bin:system/etc/firmware/nvavp_vid_ucode.bin \
    vendor/lge/p880/proprietary/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    vendor/lge/p880/proprietary/etc/firmware/fw_bcmdhd_p2p.bin:system/etc/firmware/fw_bcmdhd_p2p.bin \
    vendor/lge/p880/proprietary/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    vendor/lge/p880/proprietary/etc/firmware/BCM4330B1_002.001.003.0550.0633.hcd:system/etc/firmware/BCM4330B1_002.001.003.0550.0633.hcd \
    vendor/lge/p880/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/lge/p880/proprietary/lib/egl/libEGL_tegra_impl.so:system/lib/egl/libEGL_tegra_impl.so \
    vendor/lge/p880/proprietary/lib/egl/libGLESv2_tegra_impl.so:system/lib/egl/libGLESv2_tegra_impl.so \
    vendor/lge/p880/proprietary/lib/egl/libGLESv1_CM_tegra_impl.so:system/lib/egl/libGLESv1_CM_tegra_impl.so \
    vendor/lge/p880/proprietary/lib/libnvglsi.so:system/lib/libnvglsi.so \
    vendor/lge/p880/proprietary/lib/libnvcamerahdr.so:system/lib/libnvcamerahdr.so \
    vendor/lge/p880/proprietary/lib/libmorpho_noise_reduction.so:system/lib/libmorpho_noise_reduction.so \
    vendor/lge/p880/proprietary/lib/libnvaudioservice.so:system/lib/libnvaudioservice.so \
    vendor/lge/p880/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/lge/p880/proprietary/lib/libaudioavp.so:system/lib/libaudioavp.so \
    vendor/lge/p880/proprietary/lib/lgejpeg.so:system/lib/lgejpeg.so
