# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/vs985/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/vs985/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/lge/vs985/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/lge/vs985/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
    vendor/lge/vs985/proprietary/bin/location-mq:system/bin/location-mq \
    vendor/lge/vs985/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
    vendor/lge/vs985/proprietary/bin/quipc_main:system/bin/quipc_main \
    vendor/lge/vs985/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
    vendor/lge/vs985/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
    vendor/lge/vs985/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/lge/vs985/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/lge/vs985/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    vendor/lge/vs985/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/lge/vs985/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/lge/vs985/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/lge/vs985/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/lge/vs985/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/lge/vs985/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
    vendor/lge/vs985/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/lge/vs985/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/lge/vs985/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/lge/vs985/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
    vendor/lge/vs985/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/lge/vs985/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/lge/vs985/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
    vendor/lge/vs985/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/lge/vs985/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/lge/vs985/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/lge/vs985/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/vs985/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/vs985/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/lge/vs985/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/vs985/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
    vendor/lge/vs985/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
    vendor/lge/vs985/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/lge/vs985/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/vs985/proprietary/lib/libuicc.so:system/lib/libuicc.so \
    vendor/lge/vs985/proprietary/lib/libvss_common_idl.so:system/lib/libvss_common_idl.so \
    vendor/lge/vs985/proprietary/lib/libvss_common_iface.so:system/lib/libvss_common_iface.so \
    vendor/lge/vs985/proprietary/lib/libvss_nv_idl.so:system/lib/libvss_nv_idl.so \
    vendor/lge/vs985/proprietary/lib/libvss_nv_iface.so:system/lib/libvss_nv_iface.so \
    vendor/lge/vs985/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/lge/vs985/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/lge/vs985/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/lge/vs985/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/lge/vs985/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/lge/vs985/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/lge/vs985/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/lge/vs985/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/lge/vs985/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/lge/vs985/proprietary/vendor/lib/hw/sensors.msm8974.so:system/vendor/lib/hw/sensors.msm8974.so \
    vendor/lge/vs985/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/lge/vs985/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/lge/vs985/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/lge/vs985/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/lge/vs985/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/lge/vs985/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/lge/vs985/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/lge/vs985/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/lge/vs985/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt
