# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Projectt
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/v480/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/v480/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/lge/v480/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/lge/v480/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/lge/v480/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/lge/v480/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/lge/v480/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/lge/v480/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/lge/v480/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/lge/v480/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/lge/v480/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so
